### ISSUE TITLE
Potential attack: Inconsistency of block.number and off-chain real time

### ISSUE THREAD

**Issue by 0x3bfc** [oceanprotocol/keeper-contracts#416]
### Exploit scenario:

The mapping between real time in `seconds` off-chain and `block.number` on-chain could be inconsistent. Giving that the `average block interval` is not defined yet in PoA Ocean Network which is super fast compared to PoW. Moreover, `block.number` relies on the number of invoked transactions per block.
This means that an adversary can invoke fake transactions to reach the target block number (target timeout), which in turn enforces the fulfiller to fulfil the condition. This attack will be hard to control, especially in case of complex agreements that rely heavily on time such as computation use case.

### Short-term Mitigation
In PoA network, we trust the network verifiers, so to mitigate the risk of having this potential attack is to change `block.number` in the keeper contracts to `block.timestamp` or `now`.

**Comment by H34D** [comment]
Looks easy:

If we deploy to our own network: `block.timestamp`
if we deploy to an open network: `block.number`

**Comment by aabdulwahed** [comment]
>> if we deploy to an open network: `block.number`

@H34D in an open/public network we might have the possibility to be prone to this kind of attack. The only way  in this case is to rely on an `oracle` to verify the consistency of the real time. Despite the fact that oracle might consume some `gas/ether` to get the proof, but my concern is that having an `oracle` in the system can be a potential source for single point of failure. At any moment this oracle could be unreachable, and all the transactions that rely on this oracle will be invalid.

**Comment by H34D** [comment]
> @H34D in an open/public network we might have the possibility to be prone to this kind of attack. The only way in this case is to rely on an `oracle` to verify the consistency of the real time. Despite the fact that oracle might consume some `gas/ether` to get the proof, but my concern is that having an `oracle` in the system can be a potential source for single point of failure. At any moment this oracle could be unreachable, and all the transactions that rely on this oracle will be invalid.

ok, what do you propose?

**Comment by aabdulwahed** [comment]
It is an open question! 
- My proposal is to keep the `block.number` but with a dispute resolution mechanism for the time inconsistency as follows:

#### The timeout allocation:

2. store timeout window in seconds `uint256`. 
3. store the starting point of the timeout using `previous block.number`.

### Dispute resolution
- having the start point of the timeout (eg. `block.number=5`) get the corresponding timestamp using network API (eg. [etherscanAPI](https://api.etherscan.io/api?module=block&action=getblockreward&blockno=2165403&apikey=YourApiKeyToken)) 
- Compare the value of the `(timeout window + timestamp (block.number = 5)) >= current timestamp`

![Timeout](https://user-images.githubusercontent.com/5428661/54207214-0f31ec00-44da-11e9-8d5f-f7dedfef2220.png)


Miners won't be able to change the timestamp of old blocks but also future blocks must be within reasonable Unix time, otherwise miners are unlikely to build upon blocks with unreasonable timestamps.

### References:
- [Ethereum Wiki](https://github.com/ethereum/wiki/wiki/White-Paper#blockchain-and-mining)
