### ISSUE TITLE
Automate NPM publish

### ISSUE THREAD

**Issue by H34D** [oceanprotocol/keeper-contracts#71]

**Comment by jcortejoso** [comment]
Right now I think the versions are being managed incorrectly. `bumpversion` is used to manage the version (manually) for python files, and `release-it` is used for npm package and it is done automatically during travis job. For managing python version we determined that doing manually was better to determine if we wanted to bump `patch`, `minor` or `major` version. I guess we can do the same for npm, and we can use only one tool (`bumpversion` or `release-it`) to manage the versions in this project.

**Comment by kremalicious** [comment]
`release-it` also does the git tag, bumps the version number in `package.json`, creates a GitHub release with a changelog based on latest commit messages, and then does the npm release. All those version numbers/package releases need to be in sync, otherwise it just gets confusing for end users.

So we should either switch to automatic releases for everything, or use manual releases for everything. We could create our own release script combining `release-it` with the `bumpversion`/PyPi package release

**Comment by H34D** [comment]
is this done?

**Comment by aaitor** [comment]
Assigning to @jcortejoso and @H34D , they are checking if the CI pipeline is generating the artifacts as expected after tagging in master or develop branches.

The scope is automate the release as much as possible. IMO the PyPi, NPM and Docker releasing can be automated totally. It's okay to have a script controlling all this version bump and release wrapping pypi and npm.

**Comment by jcortejoso** [comment]
I think this is solved. Packages (included npm) are deployed whenever a new tag is pushed to github.
